resource_registry:
  OS::TripleO::Services::CephMon: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-client.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
  GlanceBackend: rbd
  GnocchiBackend: rbd
  CephConfigOverrides:
    journal_size: 5120
    max_open_files: 131072
    osd_recovery_op_priority: 3
    osd_recovery_max_active: 3
    osd_max_backfills: 1
    osd_pool_default_pg_num: 256
    osd_pool_default_pgp_num: 256
    mon_max_pg_per_osd: 1200
  CephPools:
    - {"name": backups, "pg_num": 128, "pgp_num": 128}
    - {"name": volumes, "pg_num": 1024, "pgp_num": 1024}
    - {"name": vms, "pg_num": 512, "pgp_num": 512}
    - {"name": images, "pg_num": 128, "pgp_num": 128}
  CephAnsibleDisksConfig:
    devices:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/sdi
    dedicated_devices:
      - /dev/sdj
      - /dev/sdj
      - /dev/sdj
      - /dev/sdj
      - /dev/sdk
      - /dev/sdk
      - /dev/sdk
      - /dev/sdk
    osd_scenario: non-collocated
